### ISSUE TITLE
custom remote methods do not work

### ISSUE THREAD

**Issue by karanssj4** [asaf050/loopback-pkg-ready#2]
in-build remote methods work correctly, but I couldnt get the custom rmote methods to work. I get this error when I hit an remote url

```
Unhandled error for request GET /api/ts/get?access_token=h21M3BYiIfyKgMDMUriWEmEAFBxxWMCLQZQUJMEiNnBMUnKiUB6MBQrZeHODH4DO: TypeError: Cannot read property 'apply' of undefined
    at SharedMethod.invoke (/snapshot/au_monorepo/node_modules/strong-remoting/lib/shared-method.js:270:25)
    at HttpContext.invoke (/snapshot/au_monorepo/node_modules/strong-remoting/lib/http-context.js:297:12)
    at phaseInvoke (/snapshot/au_monorepo/node_modules/strong-remoting/lib/remote-objects.js:695:9)
```

**Comment by karanssj4** [comment]
created a merge request for this #3

**Comment by asaf050** [comment]
Hi :)
Merged! Thanks
